name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - asttokens=3.0.0
  - blas=1.0
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - click=8.1.8
  - colorama=0.4.6
  - decorator=5.1.1
  - eigen=3.4.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - flask=3.1.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - graphite2=1.3.14
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipython=8.30.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - krb5=1.20.1
  - lerc=3.0
  - libabseil=20240116.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numpy=1.23.5
  - numpy-base=1.23.5
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.0.16
  - parso=0.8.4
  - pcre2=10.42
  - pip=25.1
  - pixman=0.40.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - pygments=2.19.1
  - python_abi=3.10
  - qt-main=5.15.2
  - scikit-learn=1.7.0
  - scipy=1.15.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - certifi
    - charset-normalizer
    - contourpy
    - cycler
    - filelock
    - fonttools
    - fsspec
    - grpcio
    - grpcio-tools
    - idna
    - kiwisolver
    - matplotlib
    - mpmath
    - networkx
    - packaging
    - pandas
    - pillow
    - protobuf
    - psutil
    - py-cpuinfo
    - pyparsing
    - python-dateutil
    - pytz
    - pyyaml
    - requests
    - sympy
    - torch
    - torchaudio
    - torchvision
    - tqdm
    - tzdata
    - ultralytics
    - ultralytics-thop
    - urllib3